# Generated by Django 3.2.7 on 2023-05-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyviews',
            old_name='propery',
            new_name='property',
        ),
    ]
