#!/bin/bash

set -o errexit

set -o nounset

worker_ready() {
  celery -A real_estate inspect ping
}

until worker_ready; do
  echo >&2 'Celery worker not available :-('
  sleep 1
done
echo >&2 'Celery workers are available and ready!...:-)'

flower \
  --app=real_estate \
  --broker=${CELERY_BROKER}
